config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # This might break it (EDIT: it doesn't, but doesn't use the profile url)
  resources :users do
  end
  
  resources :pets do
    resources :enquiries, only: [:new, :create]
    resources :favorite_pets
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    resources :messages, only: :create
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :enquiries, only: [:index, :show, :edit, :update, :destroy]
  get 'profile', action: :show, controller: 'users'
  get 'preference', action: :edit, controller: 'users'
  get 'update_preferences', to: "users#update_preferences", as: "update_preferences"

  root to: 'pages#home'
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :enquiries

  has_many :favorite_pets
  # has_many :favorited_by, through: :favorite_pets, source: :user

  validates :name, :address, :species, :age, :breed, :description, :status, presence: true
  validates :description, length: { maximum: 500, too_long: "%{count} characters is the maximum allowed" }
  has_many_attached :photos

  def match_pets(user)
    matching = 0
    points = 25
    matching += 5 if self.breed == user.breed || user.breed == "no preference"
    matching += 5 if self.sex == user.sex || user.sex == "no preference"
    matching += 4 if self.special_needs == user.special_needs
    matching += 5 if self.age == user.age || user.age == 0
    matching += 3 if self.garden == user.garden || self.garden == false
    matching += 1 if self.other_pets == user.other_pets || self.other_pets == true
    matching += 1 if self.other_children == user.other_children || self.other_pets == true
    matching += 1 if self.available_time == user.available_time
    matching_percentage = matching.to_f / points * 100
    matching_percentage.to_i
  end

  CATBREED = ["Abyssinian Cat",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "American Wirehair",
    "Balinese cat",
    "Bengal",
    "Birman",
    "Bombay",
    "British Longhair",
    "British Shorthair",
    "Burmese",
    "Californian Rex",
    "Chartreux",
    "Chinchilla Persian",
    "Cornish Rex",
    "Cymric",
    "Devon Rex",
    "Domestic shorthair",
    "Donskoy",
    "Egyptian Mau",
    "European Shorthair",
    "Exotic shorthair",
    "German Rex",
    "Himalayen",
    "Khao Manee",
    "Maine Coon",
    "Munchkin",
    "Nebelung",
    "Norwegian Forest cat",
    "Oriental",
    "Persian",
    "Peterbald",
    "Ragdoll",
    "Russian Blue",
    "Safari",
    "Scottish Fold",
    "Siamese Cat",
    "Siberian cat",
    "Singapura",
    "Snowshoe",
    "Somali",
    "Sphynx",
    "Tonkinese",
    "Toyger",
    "Turkish Angora",
    "Turkish Van",
    "York Chocolate"]

  DOGBREED = [
    "Airedale terrier",
    "Akita",
    "Alaskan Malamute",
    "American Staffordshire terrier",
    "American water spaniel",
    "Australian cattle dog",
    "Australian shepherd",
    "Australian terrier",
    "Basset hound",
    "Beagle",
    "Bearded collie",
    "Bedlington terrier",
    "Bernese mountain dog",
    "Bloodhound",
    "Border collie",
    "Border terrier",
    "Boston terrier",
    "Boxer",
    "Bull terrier",
    "Bulldog",
    "Bullmastiff",
    "Chihuahua",
    "Chinese shar-pei",
    "Chow chow",
    "Cocker spaniel",
    "Collie",
    "Curly-coated retriever",
    "Dachshund",
    "Dalmatian",
    "Doberman pinscher",
    "English cocker spaniel",
    "English setter",
    "English springer spaniel",
    "Fox terrier",
    "Foxhound",
    "French bulldog",
    "German shepherd",
    "German shorthaired pointer",
    "German wirehaired pointer",
    "Golden retriever",
    "Great Dane",
    "Greyhound",
    "Irish setter",
    "Irish water spaniel",
    "Irish wolfhound",
    "Jack Russell terrier",
    "Japanese spaniel",
    "Labrador retriever",
    "Lakeland terrier",
    "Maltese",
    "Manchester terrier",
    "Mastiff",
    "Norwich terrier",
    "Pomeranian",
    "Poodle",
    "Pug",
    "Rottweiler",
    "Saint Bernard",
    "Samoyed",
    "Schnauzer",
    "Scottish deerhound",
    "Scottish terrier",
    "Siberian husky",
    "Staffordshire bull terrier",
    "Weimaraner",
    "Welsh terrier",
    "Yorkshire terrier"]
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  
  def index
    if current_user && current_user.species != "no preference"
      @top_pets = Pet.where(species: current_user.species).sort_by{ |pet| -pet.match_pets(current_user) }
      @pets = @top_pets.drop(1)
      @top_pet = @top_pets.first
    else
      @pets = Pet.all
    end
    @user = current_user
    @users = User.all
    @markers = @users.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        info_window: render_to_string(partial: "info_window", locals: { user: user })
      }
    end
  end

  def show
    @pet = Pet.find(params[:id])
    session[:pet_id] = @pet.id
    if current_user && current_user.species != "no preference"
      @pets = Pet.where(species: current_user.species).where.not(id: @pet.id).sort_by{ |pet| -pet.match_pets(current_user) }
      @selected_pets = @pets.first(9)
    else
      @selected_pets = Pet.where(species: @pet.species).where.not(id: @pet.id).first(9)
    end
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
  end

private
  def pet_params
    params.require(:pet).permit(:name, :species, :age, :sex, :breed, :description, :address, :cost, photos: [])
  end

end

app/views/pets/_info_window.html.erb
<div class="map-card">
  <h3><%= user.company_name %></h3>
  <p><%= user.address %></p>
</div>

app/views/pets/index.html.erb
<div id="main-container">
  <div id="pet-container">
    <h1>Meet our pets </h1>
    <hr>
    <% if current_user && current_user.species != "no preference"  %>
      <br>
      <h3 style="font-size: 20px; font-weight:bolder; margin: 0px 24px 12px 0px;">Your Top Match: </h3>
      <div class="pet-card-container " data-aos="fade-up">
        <%= link_to pet_path(@top_pet.id) do %>
          <div class="pet-card top-pet">
            <div class="left-card">
              <%= cl_image_tag @top_pet.photos.first.key, height: 245, width: 285, crop: :fill, :class=> 'img-container'%>
            </div>
            <div class="right-card">
              <div style="display:flex; justify-content:space-between; margin-top: 8px;" >
                <div>
                  <p style="font-size: 12px;"><%= @top_pet.user.company_name.presence || @top_pet.user.first_name %></p>
                  <p style="font-size: 10px; font-weight: lighter; color: grey; padding-bottom: 8px;"><%= @top_pet.user.address %></p>
                </div>
                <div>
                  <% if current_user && current_user.species != "no preference" %>
                    <p style="color: white;"id="matching"><%= @top_pet.match_pets(current_user) %>%</p>
                    <p style=" text-align: center;font-size: 12px; font-weight: lighter; color: white; margin-bottom: 0px;">Match</p>
                  <% end %>
                </div>
              </div>
              <p style="font-size: 24px; margin-bottom: 0px;"><%= @top_pet.name %></p>
              <p style="font-size: 12px; font-weight: bolder; margin-bottom: 0px;"><%= @top_pet.breed %></p>
              <p style="font-size: 11px; font-weight: lighter; padding-bottom: 6px;"><%= @top_pet.age %><%= @top_pet.age > 1 ? ' years old' : ' year old' %></p>
              <p style="width: 80%;font-size: 10px; font-weight: lighter; font-style: italic; padding-bottom: 12px;"><%= @top_pet.description.slice(0, 100)%>...</p>
              <div style="float: right;">
                <p style="font-size: 10px; font-weight: lighter;">Adoption fee:</p>
                <p style="font-size: 12px; font-weight: bolder; text-align: right;">£<%= @top_pet.cost %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <br> <br> <br>
      <h1>Other pets that match your profile: </h1>
    <% end %>

    <% @pets.each do |pet| %>
      <div class="pet-card-container" data-aos="fade-up">
        <%= link_to pet_path(pet.id) do %>
          <div class="pet-card">
            <div class="left-card">
              <%= cl_image_tag pet.photos.first.key, height: 245, width: 285, crop: :fill, :class=> 'img-container'%>
            </div>
            <div class="right-card">
              <div style="display:flex; justify-content:space-between; margin-top: 8px;" >
                <div>
                  <p style="font-size: 12px;"><%= pet.user.company_name.presence || pet.user.first_name %></p>
                  <p style="font-size: 10px; font-weight: lighter; color: grey; padding-bottom: 8px;"><%= pet.user.address %></p>
                </div>
                <div>
                  <% if current_user && current_user.species != "no preference" %>
                    <p id="matching"><%= pet.match_pets(current_user) %>%</p>
                    <p style="text-align: center; font-size: 12px; font-weight: lighter; color: grey;">Match</p>
                  <% end %>
                </div>
              </div>
              <p style="font-size: 24px; margin-bottom: 0px;"><%= pet.name %></p>
              <p style="font-size: 12px; font-weight: bolder; margin-bottom: 0px;"><%= pet.breed %></p>
              <p style="font-size: 11px; font-weight: lighter; padding-bottom: 6px;"> <%= pet.age %><%= pet.age > 1 ? ' years old' : ' year old' %></p>
              <p style=" width: 80%; font-size: 10px; font-weight: lighter; font-style: italic; padding-bottom: 12px;"><%= pet.description.slice(0, 100)%>...</p>
              <div style="float: right;">
                <p style="font-size: 10px; font-weight: lighter;">Adoption fee:</p>
                <p style="font-size: 12px; font-weight: bolder; text-align: right;">£<%= pet.cost %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <hr>
    <% end %>
  </div>
  <div style=" width: 520px;">
    <div>
      <%= render 'users/edit' %>
    </div>
    <div id="map"
         style=" margin: 0px 24px 24px 24px; width: 100%;
         position: sticky; top: 100px;
         height: 550px; box-shadow: 0 0 10px rgba(0,0,0,0.15);"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/pets/petworkings.html.erb
  <div id="carouselExampleIndicators"  class="carousel slide container" data-ride="carousel" style="background-color:grey">
  <ol class="carousel-indicators">
    <% @pet.photos.each_with_index do |photo, index| %>
      <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= index == 0 ? 'active' : '' %>"></li>
    <% end %>
    <% <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li> %>
  </ol>
  
  <div class="carousel-inner">
    <% @pet.photos.each_with_index do |photo, index| %>
      <div class="carousel-item <%= 'active' if index == 0 %>"> 
        <%= cl_image_tag photo.key, height: 500, width: 600,  crop: :fit %>      
      </div>
    <%end%>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/pets/show.html.erb
<div id="pet-show-container" style="width: 1200px; margin: auto; padding-top: 20px;">


  <div id="pet-image-container">
    <div>
      <%= link_to "Back to pets", pets_path, class: "back" %>
      
    </div>
    <br>
    <div class="pet-show-title" style="display:flex; justify-content:space-between;">
        <h1>Meet <%= @pet.name %></h1>
        <div class="add-favorite" style="float: right;">
          <% if FavoritePet.where(user: current_user, pet: @pet).any? %>
              <i class="fas fa-heart favourite-button"></i>
          <% else %>
            <%= link_to pet_favorite_pets_path(@pet), method: 'post' do %>
              <i class="far fa-heart favourite-button"></i>
            <% end %>
          <% end %>
        </div>
    </div>
      <br><br>
    <div id="multi-item-example" class="carousel slide carousel-multi-item" data-ride="carousel" >

      <!--Controls-->

     
      
      
      <div class="controls-top">
        
        
      </div>
      <!--/.Controls-->

      <!--Indicators-->
      <ol class="carousel-indicators">
        <li data-target="#multi-item-example" data-slide-to="0" class="active"></li>
        <li data-target="#multi-item-example" data-slide-to="1"></li>
        <li data-target="#multi-item-example" data-slide-to="2"></li>
      </ol>
      <!--/.Indicators-->
      <div class="carousel-wrapper" >
        <a class="btn-floating" href="#multi-item-example" data-slide="prev"><i class="fa fa-chevron-left"></i></a>
        <div class="carousel-inner" role="listbox">
          <% slice = @pet.photos.each_slice(3).to_a %>
          <div class="carousel-item active">
            <div class="row">
              <div class="col-md-4">
                <div class="mb-2 pet_image" style="background-image: url('<%= cl_image_path slice.first.first.key %>')">
                </div>
              </div>
              <% slice.first[1..-1].each do |photo| %> 
                <div class="col-md-4 clearfix d-none d-md-block"> 
                  <div class="mb-2 pet_image" style="background-image: url('<%= cl_image_path photo.key %>')">
                  </div>
                </div>
              <%end%>
            </div>
          </div>
          <% slice[1..-1].each do |min_slice| %>
            <div class="carousel-item">
              <div class="row">
                <div class="col-md-4">
                  <div class="mb-2 pet_image" style="background-image: url('<%= cl_image_path min_slice.first.key %>')">
                  </div>
                </div>
                  <% min_slice[1..-1].each do |photo| %> 
                    <div class="col-md-4 clearfix d-none d-md-block"> 
                      <div class="mb-2 pet_image" style="background-image: url('<%= cl_image_path photo.key %>')">
                      </div>
                    </div>
                  <%end%>   
                </div>
              </div>
          <% end %>
        </div>
        <a class="btn-floating" href="#multi-item-example" data-slide="next"><i class="fa fa-chevron-right"></i></a>
      </div>
      <!--/.Slides-->
    </div>
  

    <%# <div>
      <% @pet.photos.each do |photo| %>
        <%# <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
      <%# <%end%>
    <%# </div> %>
    <div style="display: flex; justify-content: space-between; col-12 col-lg-8; margin-top: 24px; margin-bottom: 24px">
      <div style="font-weight: 300; font-size: 13px; padding-right: 36px; margin-top: 24px">
      <br><br>
        <h4 style="font-size: 22px;">About me</h4>
        <hr>
        <div class="pet-show-about">
          <ul>
            <li style="font-size:14px; font-weight:bold"><%= @pet.breed.capitalize %></li>
            
            
           <li><%= @pet.age %><%= @pet.age > 1 ? ' years old' : ' year old' %></li>
            
            
           <li><%= @pet.sex.capitalize%></li>
            
            
          </ul>
        </div>
        <br><br>
        <div>
          <hr>
          
          <p style="font-style: italic; font-size: 14px;"><%= @pet.description %></p>
          <hr>
          <p>(*) To meet <%= @pet.name %> chat with <%= @pet.user.company_name %></p>
        </div>
        <br>

        
      </div>

      <div class="pet-info-show-2 col-12 col-lg-5 d-flex flex-column" >
        <div class="adopt-style">
          <h4 style="font-size:12px; font-weight:lighter">Availability:</h4>
          <% if @pet.status == "available" %>
            <p><i class="fas fa-check" style="color: #FFCB74"></i></p>
          <% else %>
            <p><i class="fas fa-times" style="color: #FFCB74"></i><p>
          <% end %>
        </div>
        <hr class="w-100">
          <div class="adopt-style">
            <h4 style="font-size:12px; font-weight:lighter">Adoption Fee:</h4>
            <p>£<%= @pet.cost %></p>           
          </div>
          <hr class="w-100">
          <div class="adopt-style">
            <h4 style="font-size:12px; font-weight:lighter">Adoption Centre:</h4>
            <p><%= @pet.user.company_name %></p>
          </div>
          <br>
          <div class="adopt-style">
            <h4></h4>
            <p style="font-weight:normal;"><%= @pet.address %></p>
            
          </div>
          <hr class="w-100">
          <!-- for post request, use simple form for. We WERE using wrong params -->
            <div class="d-flex justify-content-between align-items-end flex-grow-1">
              <p class='booking-btn mb-0'><i class="far fa-calendar-alt"></i><%= link_to " Book a play date", new_pet_enquiry_path(@pet) %></p>
              <%= simple_form_for Conversation.new do |f| %>
                <%= f.hidden_field :recipient_id, value: @pet.user.id %>
                <%= f.submit "Chat with the owner" %>
              <% end %>
            </div>
      </div>
    </div>
    <div class="pet-info-show" >
          
          <div style="display: flex; justify-content: space-between; col-12 col-lg-6; font-weight: 300; font-size: 13px;"  class="pet-show-important">
            <ul>
             <li><i class="fas fa-seedling"></i>
                <% if @pet.garden == true %>
                  <%= "I need a garden" %>
                <% else %>
                  <%= "I can live in an apartment" %>
                <%end%>
             </li>
              <br>
              <li><i class="fas fa-baby"></i>
                <% if @pet.other_children == true %>
                  <%= "I can live with children" %>
                <% else %>
                  <%= "Sorry I'm not suitable to live with children :(" %>
                <%end%>
              </li>
                  <br>
              <li><i class="fas fa-cat"></i>
                <% if @pet.other_pets == true %>
                  <%= "I love to live with other pets" %>
                <% else %>
                  <%= "Im not great with other pets" %>
                <%end%>
              <br>
              </li>
            </ul>
            <div>
              <ul >
                <li> <i class="fas fa-first-aid"></i>
                  <% if @pet.special_needs == true %>
                    <%= "I require extra care. Please ask my carer for details" %>
                  <% else %>
                    <%= "I do not require any special care" %>
                  <%end%>
                </li> 
                <br>
                <li><i class="fas fa-home"></i>
                  <% if @pet.available_time == 1 %>
                    <%= "I can be left unattended up to 3 hours per day" %>
                  <% elsif @pet.available_time == 2 %>
                    <%= "I can be left unattended up to 6 hours per day" %>
                  <% elsif @pet.available_time == 3 %>
                    <%= "I can be left unattended up to 10 hours per day" %>
                  <% elsif @pet.available_time == 4 %>
                    <%= "I can be left unattended for more than 10+ hours per day" %>
                  <%end%>
                </li>
                <br>
                <li><i class="fas fa-dog"></i> Can be pet tested </li>
                <br>
              </ul>
            </div>
          </div>  
        </div>
      <div>
    </div>
  </div>  
</div>
<div style="margin-top:0px; font-weight: 400;" class="slider-container">
  <h1>More Pets Like <%= @pet.name %></h1>
  <%= render 'shared/carousel' %>
</div>