config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # This might break it (EDIT: it doesn't, but doesn't use the profile url)
  resources :users do
  end
  
  resources :pets do
    resources :enquiries, only: [:new, :create]
    resources :favorite_pets
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    resources :messages, only: :create
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :enquiries, only: [:index, :show, :edit, :update, :destroy]
  get 'profile', action: :show, controller: 'users'
  get 'preference', action: :edit, controller: 'users'
  get 'update_preferences', to: "users#update_preferences", as: "update_preferences"

  root to: 'pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sent_conversations, class_name: "Conversation", foreign_key: :sender_id
  has_many :sent_conversation_messages, through: :sent_conversations, source: :messages

  has_many :received_conversations, class_name: "Conversation", foreign_key: :recipient_id
  has_many :received_conversation_messages, through: :received_conversations, source: :messages

  has_many :favorite_pets, dependent: :destroy
  # has_many :favorites, through: :favorite_pets, source: :pet

  has_many :pets
  has_many :enquiries
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  CATSPECIES = ["Abyssinian Cat",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "American Wirehair",
    "Balinese cat",
    "Bengal",
    "Birman",
    "Bombay",
    "British Longhair",
    "British Shorthair",
    "Burmese",
    "Californian Rex",
    "Chartreux",
    "Chinchilla Persian",
    "Cornish Rex",
    "Cymric",
    "Devon Rex",
    "Domestic shorthair",
    "Donskoy",
    "Egyptian Mau",
    "European Shorthair",
    "Exotic shorthair",
    "German Rex",
    "Himalayen",
    "Khao Manee",
    "Maine Coon",
    "Munchkin",
    "Nebelung",
    "Norwegian Forest cat",
    "Oriental",
    "Persian",
    "Peterbald",
    "Ragdoll",
    "Russian Blue",
    "Safari",
    "Scottish Fold",
    "Siamese Cat",
    "Siberian cat",
    "Singapura",
    "Snowshoe",
    "Somali",
    "Sphynx",
    "Tonkinese",
    "Toyger",
    "Turkish Angora",
    "Turkish Van",
    "York Chocolate"]

  DOGSPECIES = [
    "Airedale terrier",
    "Akita",
    "Alaskan Malamute",
    "American Staffordshire terrier",
    "American water spaniel",
    "Australian cattle dog",
    "Australian shepherd",
    "Australian terrier",
    "Basset hound",
    "Beagle",
    "Bearded collie",
    "Bedlington terrier",
    "Bernese mountain dog",
    "Bloodhound",
    "Border collie",
    "Border terrier",
    "Boston terrier",
    "Boxer",
    "Bull terrier",
    "Bulldog",
    "Bullmastiff",
    "Chihuahua",
    "Chinese shar-pei",
    "Chow chow",
    "Cocker spaniel",
    "Collie",
    "Curly-coated retriever",
    "Dachshund",
    "Dalmatian",
    "Doberman pinscher",
    "English cocker spaniel",
    "English setter",
    "English springer spaniel",
    "Fox terrier",
    "Foxhound",
    "French bulldog",
    "German shepherd",
    "German shorthaired pointer",
    "German wirehaired pointer",
    "Golden retriever",
    "Great Dane",
    "Greyhound",
    "Irish setter",
    "Irish water spaniel",
    "Irish wolfhound",
    "Jack Russell terrier",
    "Japanese spaniel",
    "Labrador retriever",
    "Lakeland terrier",
    "Maltese",
    "Manchester terrier",
    "Mastiff",
    "Norwich terrier",
    "Pomeranian",
    "Poodle",
    "Pug",
    "Rottweiler",
    "Saint Bernard",
    "Samoyed",
    "Schnauzer",
    "Scottish deerhound",
    "Scottish terrier",
    "Siberian husky",
    "Staffordshire bull terrier",
    "Weimaraner",
    "Welsh terrier",
    "Yorkshire terrier"]

  def unread_messages
    sent_conversation_messages.where.not(user: self, read: true).count + received_conversation_messages.where.not(user: self, read: true).count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @conversations = Conversation.where(sender: current_user).or(Conversation.where(recipient: current_user))
    @favorite_pets = FavoritePet.where(user_id: current_user)
  end

  # enquires on my pets is current_user.pets.enquiries
  def edit
    @user = current_user
  end

  def update_preferences
    @user = current_user
    if current_user.save!
      current_user.update(user_params)
      redirect_to pets_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :breed,
      :age,
      :sex,
      :other_pets,
      :other_children,
      :available_time,
      :garden,
      :special_needs,
      :species)
  end
end

app/views/users/_edit.html.erb
<% if current_user %>
  <div class="preferences">
    <div style="display:flex; justify-content:space-between;">
      <h3 style="font-size: 14px; font-weight: bolder; padding-bottom: 12px">Your perfect pet is just a few clicks away!</h3>
      <i class="fas fa-arrow-down" data-toggle="collapse" data-target="#demo" style="padding-top: 4px; font-size: 14px;"></i>
     <!--  <button data-toggle="collapse" data-target="#demo">
        <i class="fas fa-arrow-down"></i>
      </button> -->
    </div>

    <%= simple_form_for(@user , url: update_preferences_path, :method => :get) do |f| %>
      <div id="demo" class="collapse">
        <%#= f.input :address, label: "Location:"%>
        <%= f.input :species,label: "What are you interested in?", collection: [['Cat', "cat"], ['Dog', "dog"], ['Rodent',"rodent"], ['No preference','no preference']],
                      as: :radio_buttons,
                      input_html: { class: "tag-selector" },
                      item_wrapper_class: 'tag-item' %>
        <%#= f.input :breed, label: "Prefered Dog Breed", collection: Pet::DOGBREED %>
        <%= f.input :sex, label: "", collection: [["Male","male"], ["Female","female"], ['No preference','no preference']],
                      as: :radio_buttons,
                      input_html: { class: "tag-selector" },
                      item_wrapper_class: 'tag-item' %>
        <%#= f.input :breed, label: "Prefered Cat Breed", collection: Pet::CATBREED %>
        <hr style="margin-top:12px; margin-bottom:12px;">
        <%= f.input :age, label: "Do you have a prefered age?", :collection => [['0-1', 1], ['1-7', 2], ['7-12', 3], ['+12', 4], ['No preference', 0]],
                      as: :radio_buttons,
                      input_html: { class: "tag-selector" },
                      item_wrapper_class: 'tag-item' %>
        <%= f.input :available_time, label: "How many hours are you away each day?", :collection => [['0-3', 1], ['3-6', 2], ['6-10', 3], ['+10', 4]],
                      as: :radio_buttons,
                      input_html: { class: "tag-selector" },
                      item_wrapper_class: 'tag-item' %>
        <hr style="margin-top:12px; margin-bottom:12px;">
        <div style="display: flex; flex-wrap: wrap">
          <%= f.input :garden, label: "Do you have a garden?", :collection => [['Garden', true], ["No Garden", false]],
                        as: :radio_buttons,
                        input_html: { class: "tag-selector" },
                        item_wrapper_class: 'tag-item' %>
          <%= f.input :other_pets, label: "Other pets?", :collection => [['Have other pets', true], ["Don't have other pets", false]],
                        as: :radio_buttons,
                        input_html: { class: "tag-selector" },
                        item_wrapper_class: 'tag-item' %>
          <%= f.input :other_children, label: "Do you have children?", :collection => [['Have children', true], ["Don't have children", false]],
                        as: :radio_buttons,
                        input_html: { class: "tag-selector" },
                        item_wrapper_class: 'tag-item' %>
          <%= f.input :special_needs, label: "Are you interested in a pet with special needs?", :collection => [["Interested in pet with special needs", true], ["Not interested in pets with special needs", false]],
                        as: :radio_buttons,
                        input_html: { class: "tag-selector" },
                        item_wrapper_class: 'tag-item' %>
        </div>
      </div>
      <hr>
      <%= f.submit "Apply" %>
    <% end %>
  </div>

<% end %>

app/views/users/show.html.erb
<div style="margin: 120px 150px 24px 48px;">
    <%= link_to "Back to pets", pets_path, class: "back" %>
</div>
  <div class="container-profile" style=" margin: 0px 150px 0px 0px;padding: 0px; display:flex; justify-content:flex-start;">
    <div class="profile-banner flex-shrink-0 sticky-top">
      <div class="profile-img">
        <%= cl_image_tag current_user.photo.key, height: 150, width: 150,  crop: :fill %>
      </div>
      <div class="profile-info">
        <div id="profile-name">
          <span><%= current_user.first_name %></span>
          <span><%= current_user.last_name %></span>
        </div>
        <div id="profile-info-text">
          <p><%= current_user.email %></p>
          <p><%= current_user.address %></p>
          <p style="padding-top: 12px;">Hey, I'm Linda! My partner and I are really interested in adopting a rescue dog. We're a family of 4 with 2 young children and plenty of outdoor space. I've come to Pawsome to find the perfect pooch, and give them a perfect home.</p>
        </div>
      </div>
    </div>
    <div class="profile-right">
      <nav style="max-height: 60px;">
        <div class="nav nav-tabs " id="nav-tab" role="tablist">
          <a class="nav-link active" id="nav-contact-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="true">Favourite Pets</a>
          <a class="nav-link <%= 'tab-new' if current_user.unread_messages > 0 %>" id="nav-profile-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="false">Conversations</a>
          <a class="nav-link " id="nav-home-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Playdates</a>
        </div>
      </nav>
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade " id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
          <h2>Your Playdates</h2>
          <hr>
          <% current_user.enquiries.each do |enquiry| %>
            <div>
              <div class=" enquiry mb-2">
                <div class="enquiry-img">
                  <%= cl_image_tag enquiry.pet.photos.first.key, height: 150, width: 150, crop: :fill, :class=> 'round-img'%>
                </div>
                <div>
                  <%= link_to enquiry.pet.name, pet_path(enquiry.pet), :class => "back"%>
                  <h4>Visit date: <strong><%= enquiry.date.strftime('%A, %d %b %Y %l:%M %p') %></strong></h4>
                  <h4>Location: <strong><%= enquiry.pet.user.address %></strong></h4>
                  <p style= "font-size: 12px; font-style: italic; margin-top:16px;"><%= enquiry.pet.description %></p>
                  <%= simple_form_for Conversation.new do |f| %>
                    <%= f.hidden_field :recipient_id, value: enquiry.pet.user.id %>
                    <%= f.submit "Back to Chat with #{enquiry.pet.user.company_name}" %>
                  <% end %>
                </div>
              </div>
            </div>
            <hr>
          <% end %>
        </div>
        <div class="tab-pane fade " id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
          <h2>Your Conversations</h2>
          <hr>
          <ul class="conversation-list">
            <% @conversations.each do |c| %>
              <div class= "conversation container border">
                <% if c.messages.any? %>
                  <h4 class="conversation-link"><strong> <%= link_to c.recipient.company_name, conversation_path(c.id) %></strong> </h4>
                  <% if c.messages.last.user_id == current_user.id %>
                    <%= link_to "You wrote: #{c.messages.last.body}", conversation_path(c.id),class: "back last-msg" %>
                  <% else %>
                    <%= link_to "#{c.messages.last.user.nickname} wrote: #{c.messages.last.body}", conversation_path(c.id), class: "back last-msg" %>
                  <% end %>
                <% else %>
                  <p><%= link_to "This is a brand new conversation", conversation_path(c.id) %></p>
                <% end %>
              </div>
            <% end %>
          </ul>
        </div>
        <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
          <h2>Your favourite pets</h2>
          <hr>
          <div class ="favourite-container">
            <% @favorite_pets.each do |f| %>
              <div class=" favourite-card">
                <%= cl_image_tag f.pet.photos.first.key, height: 150, width: 150, crop: :fill, :class=> 'round-img'%>
                <div>
                  <h3 class="mb-1 mt-2"><%= f.pet.name %> </h3>
                  <p style="font-size: 14px; font-weight: bolder; margin-bottom: 0px;"><%= f.pet.breed %></p>
                  <p style="font-size: 12px; font-weight: lighter; margin-bottom: 14px;"><%= f.pet.age %><%= f.pet.age > 1 ? ' years old' : ' year old' %></p>
                  <%= link_to 'View pet', pet_path(f.pet), class: 'more-info' %>
                </div>
              </div>
              <hr>
            <% end %>
          </div>
        </div>
      </div>
     </div>
  </div>

app/views/users/toaddlater.html.erb
<h1>I am the user show page</h1>
<h2>Here are your conversations</h2>
<ul>
  <% @conversations.each do |c| %>
    <div class="container border">
      <!-- TODO: Grab the sender name from the sender_id -->
      <% if c.messages.last.user_id == current_user.id %>
        <p><%= link_to "You wrote: #{c.messages.last.body}", conversation_path(c.id) %></p>
      <% else %>
      <h4 class="font-weight-bold"><%= "New message"%></h4>
        <p><%= link_to "#{c.messages.last.user.nickname} wrote: #{c.messages.last.body}", conversation_path(c.id) %></p>
      <% end %>
    </div>
  <% end %>
</ul>