config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # This might break it (EDIT: it doesn't, but doesn't use the profile url)
  resources :users do
  end
  
  resources :pets do
    resources :enquiries, only: [:new, :create]
    resources :favorite_pets
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    resources :messages, only: :create
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :enquiries, only: [:index, :show, :edit, :update, :destroy]
  get 'profile', action: :show, controller: 'users'
  get 'preference', action: :edit, controller: 'users'
  get 'update_preferences', to: "users#update_preferences", as: "update_preferences"

  root to: 'pages#home'
end

app/views/shared/_carousel.html.erb
  <div class="controls">
    <button class="prev">
      <i class="fas fa-chevron-left"></i>
    </button>
     <button class="next">
      <i class="fas fa-chevron-right">  </i>
    </button>
  </div>
  <div class="my-slider">
    <% @selected_pets.each do |pet| %>
      <div class="slider-item">
        <div class="s-card">
          <%= link_to pet_path(pet.id) do %>
            <%= cl_image_tag pet.photos.first.key, :class=> 's-img-container'%>
          <% end %>
          <div id="s-name">
            <%= pet.name%>
          </div>
          <div class="s-pet-info">
            <p style="font-size: 13px; font-weight: bolder; margin-bottom: 0px;"><%= pet.breed %></p>
            <p style="font-size: 11px; margin-bottom: 6px;"><%= pet.user.company_name.presence || pet.user.first_name %></p>
            <div style=" display: flex; justify-content: space-between;">
              <p style="font-size: 11px; font-weight: lighter; margin-bottom: 0px"><%= pet.age %> years old</p>
              <p style="font-size: 12px; font-weight: bolder; text-align: right ; margin-bottom: 0px">£<%= pet.cost %></p>
            </div>

          </div>
        </div>
      </div>
    <% end %>
    </div>
  <div class="dots" style="text-align:center">
    <span class="dot" onclick="currentSlide(1)"></span>
    <span class="dot" onclick="currentSlide(2)"></span>
    <span class="dot" onclick="currentSlide(3)"></span>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
 <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <!-- Fix this line! -->
        <li class="nav-item ">
          <%= link_to "Messages", profile_path, class: "nav-link", id: "messages-link" %>
          <%= current_user.unread_messages %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_pawsomenavbar.html.erb
<% if current_page?('/') %>
  <nav class="navbar-transparent fixed-top">
<% else %>
  <nav class="navbar-white-none fixed-top">
<% end %>
  <div id="logo-set">
    <div id="logo">
      <%= link_to 'Pawsome', root_path, class: "logo_text" %>
      <p>Simple and Ethical Adoption</p>
      <%#= cl_image_tag("PAW_jaq0mh.png", height: 150, width: 150, crop: :fit) %>
    </div>
  </div>

      <!-- <div class="form-inline">
        </%= form_tag pets_path, method: :get do %>
          </%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a pet" %>
            </%= button_tag type: 'submit' , class: "btn btn-outline-light" do %>
              <i class="fas fa-toilet-paper"></i>
            </% end %>
        </% end %>
      </div> -->

  <div id="sign-up-section" style="display:flex">
    <% if current_user %>
      <p class="sign-up">
        Hello ,  <%= current_user.first_name %>
      </p>
      <div class="button">
        <%= link_to 'Profile', profile_path, class: "sign-up" %>
      <span class= "<%= 'new-notification' if  current_user.unread_messages > 0 %>" ></span>
      </div>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "sign-up" %>
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar-hp" %>
      <% else %>
      <% end %>
    <% else %>
      <%= link_to 'Sign up', new_user_registration_path, class: "sign-up" %>
      <%= link_to 'Login', new_user_session_path, class: "sign-up" %>
    <% end %>
  </div>
</nav>